services:
  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
      - "2345:2345"
    tty: true
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
